/*
* # terraform-module-template
*
* This repository is a template for developing Terraform modules. It has all the common structure and code that we usually use in our module repositories.
*
* All requirements and example code is automatically generated by using `terraform-docs`, and this text can be found in the `main.tf` file.
*/
