name: Automation
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
jobs:
  project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/azureterraform/projects/1
          github-token: ${{ secrets.ATFBOT_PAT }}
